(* Read a graph from a file,
 * Write a graph to a file. *)

open Graph
open Tools

type path = string

(* Writes a string graph in dot format *)
val export: path -> string graph -> unit

val export_with_clusters: path -> string graph -> id list list -> unit

(* Values are read as strings. *)
val from_file: path -> string graph

(* Similarly, we write only a string graph.
 * If necessary, use gmap (to be written by you) to prepare the input graph. *)
val write_file: path -> string graph -> unit

(* The format of files is compatible with the files generated by:
   https://algorithms.discrete.ma.tum.de/graph-algorithms/flow-ford-fulkerson/index_en.html
*)

val from_file_wishes: path -> wish list * school list